version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: flapkap-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DOCKER_DB_PORT}:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - databaseVolume:/var/lib/mysql
    networks:
      - flapkap
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  nginx:
    image: nginx:alpine
    container_name: flapkap-nginx
    restart: unless-stopped
    ports:
      - ${DOCKER_APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - flapkap

  app:
    tty: true
    build:
      args:
        user: ${DOCKER_BASH_USER}
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: flapkap
    container_name: flapkap-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/startup:/var/www/build
    networks:
      - flapkap
    depends_on:
      db: 
        condition: service_healthy

networks:
  flapkap:
    driver: bridge

volumes:
  databaseVolume: